[package]
name = "generate_top"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
simple_logger = "5.0.0"
anyhow = "1.0.99"
strum = { version = "0.27", features = ["derive"] }
serde_json = "1.0.143"
serde = { version = "1.0.219", features = ["derive"]}